### ISSUE TITLE
Exception lors de création/modification de fichier - avec la commande "recover"

### ISSUE THREAD

**Issue by Amiralgaby** [mothsART/wiki-corrector#10]
J'ai lancé la commande
`recover`

j'ai eu une exception FileNotFound

```
gabriel:~/Documents/project/wiki-corrector (main)
$ ./recover
cache/administration.dokuwiki [created]
cache/android_sdk.dokuwiki [created]
cache/apt-cli.dokuwiki [created]
cache/rosariosis.dokuwiki [created]
cache/chiffrement_manuel.dokuwiki [created]
cache/vsftpd.dokuwiki [created]
cache/utilisateurs/poupoul2.dokuwiki [deleted]
cache/empreintes_digitiales.dokuwiki [created]
cache/microsoft_office.dokuwiki [created]
cache/openshot.dokuwiki [created]
cache/visionneuse.dokuwiki [created]
cache/wiki.dokuwiki [created]
cache/migration.dokuwiki [created]
cache/shotcut.dokuwiki [created]
cache/integration_qt_gtk.dokuwiki [created]
cache/logrotate.dokuwiki [created]
cache/freefilesync.dokuwiki [created]
cache/exiv2.dokuwiki [created]
cache/lien_physique_et_symbolique.dokuwiki [created]
cache/vst.dokuwiki [created]
cache/msmtp.dokuwiki [created]
cache/flasher_le_bios.dokuwiki [created]
cache/tutoriel/boot-info.dokuwiki [created]
cache/boot-repair.dokuwiki [created]
cache/foremost.dokuwiki [created]
cache/xrdp.dokuwiki [created]
cache/bacula.dokuwiki [created]
cache/uefi.dokuwiki [created]
cache/macbook.dokuwiki [created]
cache/son_cartes_son.dokuwiki [created]
cache/wiki/modeles/utilisateur.dokuwiki [created]
cache/utilisateurs/u120.dokuwiki [created]
cache/nod32.dokuwiki [created]
cache/utilisateurs/amiralgaby.dokuwiki [created]
cache/utilisateurs/francis_gernet.dokuwiki [created]
cache/archon.dokuwiki [created]
cache/bash.dokuwiki [created]
cache/audacity.dokuwiki [created]
cache/spotify.dokuwiki [created]
cache/nextcloud.dokuwiki [created]
cache/hosts.dokuwiki [created]
cache/personnaliser_path.dokuwiki [created]
cache/utilisateurs/adedidou.dokuwiki [created]
cache/kdenlive.dokuwiki [created]
cache/kernel.dokuwiki [created]
cache/visual_boy_advance.dokuwiki [created]
cache/pdftk.dokuwiki [created]
cache/webcam.dokuwiki [created]
cache/clamav.dokuwiki [created]
cache/ffmpeg.dokuwiki [created]
cache/vdirsyncer.dokuwiki [created]
cache/tutoriel/gestion_utilisateurs_et_groupes_en_ligne_de_commande.dokuwiki [created]
cache/scripts_utiles.dokuwiki [created]
cache/boinc.dokuwiki [created]
cache/irssi.dokuwiki [created]
cache/configurer/kde-plasma-transparence-fenetre.dokuwiki [created]
Traceback (most recent call last):
  File "./recover", line 176, in <module>
    get_diff(index['last_date'])
  File "./recover", line 164, in get_diff
    download_page(value['href'], True)
  File "./recover", line 46, in download_page
    with open(path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/configurer/kde-plasma-transparence-fenetre.dokuwiki'
```

J'ai l'impression que le souci vient du fait que le dossier 'configurer' n'existe pas. Je n'ai pas fait de recherche

**[EDIT]**

Cela venait bien du fait que le dossier 'configurer' n'existait pas

**Comment by mothsART** [comment]
corrigé ici https://github.com/mothsART/wiki-corrector/commit/b34991cc3b29dc78d5dbe0b868d8fa43ea93e8b0
